# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    hostname: db
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysqldata:/var/lib/mysql
      # - ./initdb:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=springer
      - MYSQL_USER=springer
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
  
volumes:
  mysqldata: null